server:
  port: 8080
spring:
  freemarker:
    #设置编码格式
    charset: utf-8
    #设置文件后缀
    suffix: .ftl
    #设置ftl文件路径
    template-loader-path: classpath:/templates
    #关闭缓存，及时刷新，上线生产环境需要改为true
    cache: false
  mvc:
    view:
      suffix: /templates